### ISSUE TITLE
Add option to configure or provide window split configuration

### ISSUE THREAD

**Issue by kristijanhusak** [jfonseca8/vim-bujo#12]
Hi,

it would be good to be able to either add some configuration for the split window, or provide ability to use `<mods>`.

Edit: Unrelated, but I noticed that each time i write a buffer, it adds a line to the end.

**Comment by vuciv** [comment]
Yes, I have been procrastinating adding user configurations. I will do that ASAP. Thanks for your input and I hope you enjoy :)

**Comment by vuciv** [comment]
@kristijanhusak Can you give me some examples of how you would want to use config or mod?

I just want to make sure I get this right, and suited to users' preferences.

**Comment by kristijanhusak** [comment]
There could be two things:

* Variable that will determine the window width, something like `let g:bujo_window_width = 30`
* Provide `<mods>` so you can do something like `vertical topleft Todo`.

**Comment by vuciv** [comment]
@kristijanhusak Both of these features have been implemented. Thank you for your input. 

Please enjoy and let me know if there are any issues.
