### ISSUE TITLE
Autoformatting is a bit annoying

### ISSUE THREAD

**Issue by ThePrimeagen** [jfonseca8/vim-bujo#14]
When I save the following happens.

1. characters get escaped ($, _, etc etc).
2. Cursor is moved to the bottom line (always 2 blank lines at the bottom).
3. Double spaces are not allowed.  If I have "  this  ".  It will be changed to " this ".

Is there anyway we can remove the auto formatter?

**Comment by vuciv** [comment]
Yes, absolutely. Thanks for the input; I'm on this asap!

**Comment by vuciv** [comment]
@ThePrimeagen It should be gone now. You were definitely right about these; it was probably feature creep kicking in.

If there are any issues, please let me know.
