### ISSUE TITLE
Add signs column

### ISSUE THREAD

**Issue by marcosmcz** [jfonseca8/vim-bujo#16]
Great plugin.

Can you add a signs column that points a TODO item with the line/lines of code that the item references.

It would be great to open a buffer and have a sign that the user knows is a TODO item and needs to get done.

Thanks.

**Comment by vuciv** [comment]
Hello! I am glad that you are enjoying the plugin.

I believe I understand what you are asking but just to be sure, can you give an example?

**Comment by vuciv** [comment]
Hey, @marcoscz1995. So, I have thought about this 

The purpose of this plugin is to provide a general todo list. I believe if you want todo lists associated with specific line numbers, I believe it is better practice to just put a todo at that line. 

So, in all. This is beyond the scope of this project. I appreciate you taking the time to use this plugin, and hope that you continue to enjoy it.
