### ISSUE TITLE
Trouble installing via `Vundle`

### ISSUE THREAD

**Issue by jhod0** [jfonseca8/vim-bujo#20]
I wasn't able to install vim-bujo via [Vundle](https://github.com/VundleVim/Vundle.vim), running `:Plugin 'vuciv/vim-bujo'` and `:PluginInstall` I got the error:

```
[2020-08-16 11:37:36] > Error running :helptags /home/<me>/.vim/bundle/vim-bujo/doc
```

It looks like the error was:

```
E154: Duplicate tag "bujo.txt" in file /home/<me>/.vim/bundle/vim-bujo/doc//bujo.txt
```

and in `/home/<me>/.vim/bundle/vim-bujo/doc/tags` it looks like `bujo.txt` appears twice:
```
bujo-features	bujo.txt	/*bujo-features*
bujo-notes	bujo.txt	/*bujo-notes*
bujo-overview	bujo.txt	/*bujo-overview*
bujo.txt	bujo.txt	/*bujo.txt*
bujo.txt	bujo.txt	/*bujo.txt*
```

(also - this is a neat project, it seems super helpful!)

**Comment by vuciv** [comment]
Hey! Sorry for the trouble and thanks a ton for checking out my plugin. 

Can you try the newest update?

I'm not home so I didn't get a chance to test it, but I'm hoping it'll work!

**Comment by jhod0** [comment]
Worked great, thanks!
