### ISSUE TITLE
<C-Enter> and <C-BS> is not working

### ISSUE THREAD

**Issue by sumanth-lingappa** [jfonseca8/vim-bujo#3]
Hi @vuciv , this is a very useful plugin. Thanks for writing this.

I use vim8 and I install plugins by just cloning the github in `~/.vim/pack/vendor/start/` (using native pack)

<C-Enter> and <C-BS> is not working for me

**Comment by vuciv** [comment]
Hi. Sorry about that. 

Would I be able to see your vimrc or your init.vim?

Did you add all the commands in there?

nmap <C-Enter> <Plug>BujoAddnormal
imap <C-Enter> <Plug>BujoAddinser
...etc

**Comment by mgramigna** [comment]
Here's mine:

``` vim
" ...
Plug 'vuciv/vim-bujo'
" ...

" ...

nmap <C-Enter> <Plug>BujoAddnormal
imap <C-Enter> <Plug>BujoAddinsert
nmap <C-BS> <Plug>BujoChecknormal
imap <C-BS> <Plug>BujoCheckinsert


```

I am seeing the same behavior. The `:Todo` command works fine but Ctrl+enter/ctrl+backspace does nothing

**Comment by mgramigna** [comment]
Interesting.. It might be something with my system. If I change the bindings to something like `<C-a> and <C-x>` rather than backspace and enter, it works fine

**Comment by vuciv** [comment]
I see... Some people were mentioning that different terminals interpret such commands differently.

From a reddit user: "for example, my terminal emulator sees enter, control-enter, and shift-enter as the same key"

That's a bit annoying! Thanks for keeping me updated @mgramigna :)

**Comment by vuciv** [comment]
@sumanth-lingappa Does @mgramigna solution solve your issue?

**Comment by sumanth-lingappa** [comment]
I believe it's because of my terminal. I use Windows Terminal and WSL2
If I map it to `<C-a>` and `<C-x>`, they work as expected.

But I use `screen`, I need to think on which other keys I can map these to.

Closing this issue.
Thank you @vuciv and @mgramigna for your replies.
