### ISSUE TITLE
<Plug>BujoAddnormal and other variants not working

### ISSUE THREAD

**Issue by Yrds** [jfonseca8/vim-bujo#4]
Tried to add tasks to `todo.md`, but without success. Seems like `<Plug>BujoAddnormal` does nothing.

`:Todo` is working fine.

Info:

NVIM v0.4.3 with plug

My init.vim:
```
set list
set listchars=tab:··,trail:•
set hidden
set laststatus=4
set tabstop=4
set shiftwidth=4
set expandtab
set number
set nowrap

:tnoremap <A-h> <C-\><C-N><C-w>h
:tnoremap <A-j> <C-\><C-N><C-w>j
:tnoremap <A-k> <C-\><C-N><C-w>k
:tnoremap <A-l> <C-\><C-N><C-w>l
:inoremap <A-h> <C-\><C-N><C-w>h
:inoremap <A-j> <C-\><C-N><C-w>j
:inoremap <A-k> <C-\><C-N><C-w>k
:inoremap <A-l> <C-\><C-N><C-w>l
:nnoremap <A-h> <C-w>h
:nnoremap <A-j> <C-w>j
:nnoremap <A-k> <C-w>k
:nnoremap <A-l> <C-w>l

call plug#begin()
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'vuciv/vim-bujo'
call plug#end()

map <C-l> :NERDTreeToggle<CR>

nmap <C-Enter> <Plug>BujoAddnormal
imap <C-Enter> <Plug>BujoAddinsert
nmap <C-BS> <Plug>BujoChecknormal
imap <C-BS> <Plug>BujoCheckinsert
```

Am i doing something wrong?

**Comment by vuciv** [comment]
Hi, sorry that you're running into this issue. I have not tested on NVIM, but I am going to now.

I'll have more useful help soon.

**Comment by vuciv** [comment]
Hey, @Yrds. I am still getting around to using nvim, but have you tried using a different set up mappings? That was the case for another user

https://github.com/vuciv/vim-bujo/issues/3#issuecomment-649600815

**Comment by Yrds** [comment]
Yeah it worked! Tested with `<C-a>` and `<C-x>` like mentioned in #3 

Unfortunately doesn't work with `<C-enter>` and `<C-BS>`, i really like these bindings...

If this is working on vim, maybe it's a specific problem with nvim. Tried to bind <C-Enter> with other plugin like NERDTree, and as expected it doesn't work too.

For now i think this solve problem. I personally do not mind in use a different map.

Edit: What terminal emulator are you using? I googled key binding problems with vim and i figure out depending the terminal emulator, certain key bindings are different.

In my case i am using alacritty as term

Edit 2: Tried `<A-Enter>` and worked as well, i am facing a problem with the specific combination of both Control and Enter

**Comment by vuciv** [comment]
That's awesome! I'm so glad it was fixed.

I just use the cygwin terminal on my Windows Dekstop. I tried this on my Macbook where I use iterm2, but it seemed to not work there. What a shame; I need to find new default keys to use in the README!
