### ISSUE TITLE
ASCII Art for Todo.md

### ISSUE THREAD

**Issue by aklsh** [jfonseca8/vim-bujo#8]
Hey,  
I am absolute noob in VimScript. I want to know how to make use of the md.skeleton file.

**Comment by aklsh** [comment]
Never mind. I got it.

**Comment by vuciv** [comment]
Glad you got it. Enjoy!

**Comment by baogiadoan** [comment]
how do you get it @aklsh ? I can manually copy it to the  To-Do, but not sure I have to do it every day?

**Comment by aklsh** [comment]
@mrpossible, I did a weird hack:

```
autocmd bufnewfile todo.md call append(1, '') 
autocmd bufnewfile todo.md call append(2, '  ______ ____   ____   ____') 
autocmd bufnewfile todo.md call append(3, ' /_  __ / __ \ / __ \ / __ \') 
autocmd bufnewfile todo.md call append(4, '  / /  / / / // / / // / / /') 
autocmd bufnewfile todo.md call append(5, ' / /  / /_/ // /_/ // /_/ /') 
autocmd bufnewfile todo.md call append(6, '/_/   \____//_____/ \____/.md') 
autocmd bufnewfile todo.md call append(8, 'Date: ') 
```

I don't know much of vimscript, to use template files and stuff, but observing what the given syntax (given [here](https://github.com/vuciv/vim-bujo/blob/df4d94af5f6a3434824cfd6cceaa58c56fb87877/plugin/bujo.vim#L6)) does, I understood enough to make this work.

**Comment by vuciv** [comment]
@aklsh Interesting solution!
@mrpossible You can also copy and paste whatever header you want and it will stay (as long as the todo.md file doesn't get deleted from the cache)
